# PrimeDLL

find_package(minhook REQUIRED)
find_package(libcurl REQUIRED)
find_package(silver-bun REQUIRED)
find_package(nlohmann_json REQUIRED)

add_library(PrimeDLL SHARED
            "appframework/IAppSystem.h"
            "client/diskvmtfixes.cpp"
            "client/localchatwriter.cpp"
            "client/localchatwriter.h"
			"codecs/bink/bink.cpp"
			"codecs/bink/binkread.cpp"
			"codecs/miles/core.cpp"
			"codecs/miles/core.h"
			"codecs/miles/sample.cpp"
			"common/callbacks.cpp"
			"common/callbacks.h"
            "common/globals_cvar.cpp"
            "common/globals_cvar.h"
			"core/assert.h"
			"core/basetypes.h"
			"core/init.cpp"
            "core/init.h"
            "core/hooks.cpp"
            "core/hooks.h"
            "core/macros.h"
            "dedicated/dedicated.cpp"
            "dedicated/dedicated.h"
            "dedicated/dedicatedlogtoclient.cpp"
            "dedicated/dedicatedlogtoclient.h"
            "dedicated/dedicatedmaterialsystem.cpp"
            "engine/client/client.cpp"
            "engine/client/client.h"
            "engine/server/server.cpp"
            "engine/server/server.h"
            "engine/baseserver.h"
            "engine/cdll_engine_int.cpp"
            "engine/cdll_engine_int.h"
            "engine/cl_splitscreen.cpp"
            "engine/cl_splitscreen.h"
            "engine/cmd.cpp"
            "engine/cmd.h"
            "engine/common.cpp"
            "engine/datamap.cpp"
            "engine/datamap.h"
            "engine/debugoverlay.cpp"
            "engine/debugoverlay.h"
            "engine/edict.cpp"
            "engine/edict.h"
            "engine/eiface.h"
            "engine/gl_matsysiface.cpp"
			"engine/globalvars_base.h"
            "engine/host.cpp"
			"engine/host.h"
            "engine/host_listmaps.cpp"
            "engine/hoststate.cpp"
            "engine/hoststate.h"
            "engine/ivdebugoverlay.h"
            "engine/sv_main.cpp"
			"engine/sys_dll2.cpp"
            "engine/sys_engine.cpp"
			"engine/vengineserver_impl.cpp"
			"engine/vengineserver_impl.h"
            "engine/vphysics_interface.h"
			"filesystem/basefilesystem.cpp"
			"filesystem/basefilesystem.h"
            "game/client/cdll_client_int.cpp"
            "game/client/cdll_client_int.h"
            "game/client/entity_client_tools.cpp"
            "game/client/hud_chat.cpp"
            "game/client/hud_chat.h"
            "game/client/vscript_client.cpp"
            "game/client/vscript_client.h"
            "game/server/ai_helper.cpp"
            "game/server/ai_helper.h"
            "game/server/ai_navmesh.cpp"
            "game/server/ai_navmesh.h"
            "game/server/ai_networkmanager.cpp"
            "game/server/ai_networkmanager.h"
            "game/server/ai_node.h"
            "game/server/baseanimating.h"
            "game/server/baseanimatingoverlay.h"
            "game/server/basecombatcharacter.h"
            "game/server/baseentity.h"
            "game/server/basetoggle.h"
            "game/server/enginecallback.h"
            "game/server/entitylist.cpp"
            "game/server/entitylist.h"
            "game/server/gameinterface.cpp"
            "game/server/gameinterface.h"
			"game/server/physics_main.cpp"
            "game/server/player.cpp"
            "game/server/player.h"
            "game/server/recipientfilter.cpp"
            "game/server/recipientfilter.h"
            "game/server/triggers.cpp"
            "game/server/triggers.h"
            "game/server/util_server.cpp"
            "game/server/util_server.h"
            "game/server/vscript_server.cpp"
            "game/server/vscript_server.h"
            "game/shared/vscript_shared.cpp"
            "game/shared/vscript_shared.h"
            "gameui/GameConsole.cpp"
			"gameui/GameConsole.h"
            "launcher/launcher.cpp"
			"localize/localize.cpp"
            "logging/logging.h"
            "logging/loghooks.cpp"
            "logging/loghooks.h"
            "materialsystem/cshaderglue.h"
            "materialsystem/cmaterialglue.h"
			"mathlib/bitbuf.cpp"
			"mathlib/bitbuf.h"
            "mathlib/bits.cpp"
            "mathlib/bits.h"
            "mathlib/bitvec.h"
            "mathlib/color.cpp"
            "mathlib/color.h"
            "mathlib/math_pfns.h"
            "mathlib/mathlib.h"
            "mathlib/matrix.h"
            "mathlib/quaternion.h"
            "mathlib/swap.h"
            "mathlib/vector.h"
            "mathlib/vplane.h"
            "mods/audio.cpp"
            "mods/audio.h"
            "mods/compiled/kb_act.cpp"
            "mods/compiled/modkeyvalues.cpp"
            "mods/compiled/modpdef.cpp"
            "mods/compiled/modscriptsrson.cpp"
            "mods/modmanager.cpp"
            "mods/modmanager.h"
            "mods/modsavefiles.cpp"
            "mods/modsavefiles.h"
            "networksystem/bansystem.cpp"
            "networksystem/bansystem.h"
            "networksystem/bcrypt.cpp"
            "networksystem/bcrypt.h"
            "networksystem/inetmsghandler.h"
            "networksystem/netchannel.h"
            "networksystem/atlas.cpp"
            "networksystem/atlas.h"
            "originsdk/origin.cpp"
            "originsdk/origin.h"
            "originsdk/overlay.cpp"
            "originsdk/overlay.h"
            "originsdk/stryder.cpp"
            "rtech/rson/parser.cpp"
            "rtech/rui/rui.cpp"
            "rtech/datatable.cpp"
            "rtech/datatable.h"
			"rtech/pakapi.cpp"
			"rtech/pakapi.h"
            "shared/exploit_fixes/exploitfixes.cpp"
            "shared/exploit_fixes/ns_limits.cpp"
            "shared/exploit_fixes/ns_limits.h"
            "shared/misccommands.cpp"
            "shared/misccommands.h"
            "shared/playlist.cpp"
            "shared/playlist.h"
            "tier0/commandline.cpp"
            "tier0/commandline.h"
            "tier0/dbg.cpp"
            "tier0/dbg.h"
            "tier0/fasttimer.cpp"
            "tier0/fasttimer.h"
            "tier0/filestream.cpp"
            "tier0/filestream.h"
            "tier0/language.cpp"
            "tier0/memstd.cpp"
            "tier0/memstd.h"
            "tier0/platform.h"
            "tier0/taskscheduler.cpp"
            "tier0/taskscheduler.h"
            "tier0/threadtools.h"
            "tier0/utils.cpp"
            "tier0/utils.h"
            "tier1/cmd.cpp"
            "tier1/cmd.h"
            "tier1/convar.cpp"
            "tier1/convar.h"
            "tier1/cvar.cpp"
            "tier1/cvar.h"
            "tier1/interface.cpp"
			"tier1/interface.h"
            "tier1/keyvalues.cpp"
            "tier1/keyvalues.h"
            "tier1/lzss.cpp"
            "tier1/utlmemory.h"
            "tier1/utlvector.h"
            "tier2/curlutils.cpp"
            "tier2/curlutils.h"
            "toolframework/itoolentity.h"
            "vgui/vgui_baseui_interface.cpp"
			"vgui/vgui_baseui_interface.h"
            "vscript/languages/squirrel_re/include/squirrel.h"
            "vscript/languages/squirrel_re/squirrel/sqapi.cpp"
            "vscript/languages/squirrel_re/squirrel/sqarray.h"
            "vscript/languages/squirrel_re/squirrel/sqclosure.h"
            "vscript/languages/squirrel_re/squirrel/sqcompiler.h"
            "vscript/languages/squirrel_re/squirrel/sqfunctionproto.h"
            "vscript/languages/squirrel_re/squirrel/sqlexer.h"
            "vscript/languages/squirrel_re/squirrel/sqobject.h"
            "vscript/languages/squirrel_re/squirrel/sqopcodes.h"
            "vscript/languages/squirrel_re/squirrel/sqstate.h"
            "vscript/languages/squirrel_re/squirrel/sqstring.h"
            "vscript/languages/squirrel_re/squirrel/sqstruct.h"
            "vscript/languages/squirrel_re/squirrel/sqtable.h"
            "vscript/languages/squirrel_re/squirrel/squserdata.h"
            "vscript/languages/squirrel_re/squirrel/sqvector.h"
            "vscript/languages/squirrel_re/squirrel/sqvm.cpp"
            "vscript/languages/squirrel_re/squirrel/sqvm.h"
            "vscript/languages/squirrel_re/vsquirrel.cpp"
            "vscript/languages/squirrel_re/vsquirrel.h"
            "vscript/vscript.cpp"
            "vscript/vscript.h"
            "windows/libsys.cpp"
            "windows/libsys.h"
			"windows/wconsole.cpp"
			"windows/wconsole.h"
			"windows/window.cpp"
			"Northstar.def"
)

target_link_libraries(PrimeDLL PRIVATE
                      minhook
                      libcurl
                      silver-bun
					  nlohmann_json
                      WS2_32.lib
                      Crypt32.lib
                      Cryptui.lib
                      dbghelp.lib
                      Wldap32.lib
                      Normaliz.lib
                      Bcrypt.lib
                      version.lib
)

target_precompile_headers(PrimeDLL PRIVATE core/stdafx.h)

target_compile_definitions(PrimeDLL PRIVATE
                           NORTHSTAR
						   _CRT_SECURE_NO_WARNINGS
                           UNICODE
                           _UNICODE
                           CURL_STATICLIB
# 						   CURL_STATIC_CRT
)

target_link_options(PrimeDLL PRIVATE
                    "/MANIFEST:NO" # Don't create .manifest
                    "/DEBUG"       # Create debug symbols even on release builds

					# This is needed so we can override *_dbg alloc functions
                    $<$<CONFIG:Debug>:/FORCE:MULTIPLE>
)

set_target_properties(PrimeDLL PROPERTIES
                      RUNTIME_OUTPUT_DIRECTORY ${NS_BINARY_DIR}
                      OUTPUT_NAME bin/x64_retail/Prime
                      COMPILE_FLAGS "/W4"
)
